[client]
showErrorDetails = "stacktrace"

[logger]
level = "info"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = false
enableCORS = false
corsAllowedOrigins = []
enableXsrfProtection = false

[theme]
primaryColor = "#bb5a38"
backgroundColor = "#f4f3ed"
secondaryBackgroundColor = "#ecebe3"
textColor = "#3d3a2a"
linkColor = "#3d3a2a"
borderColor = "#d3d2ca"
showWidgetBorder = true
baseRadius = "0.6rem"
codeBackgroundColor = "#ecebe4"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#e8e7dd"
secondaryBackgroundColor = "#ecebe3"